[package]
name = "touch"
version = "0.1.0"
authors = ["Liam Henrickson <liam.henrickson@gmail.com>"]
edition = "2021"

[dependencies]
common = { path = "../common" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }