[package]
name = "swap"
version = "0.1.0"
authors = ["Liam <liam.henrickson@gmail.com>"]
edition = "2018"

[profile.release]
lto = "fat"
codegen-units = 1
opt-level = "z"

[dependencies]
clap = "2"
tempdir = "0.3"
