[package]
name = "re"
version = "0.1.0"
edition = "2021"

[dependencies]
common = { path = "../common" }
anyhow = "1"
clap = { version = "4.2", features = ["derive"] }
path-clean = "1.0"
tempfile = "3.5"
